// common
export const SET_UI_ELEMENT = 'SET_UI_ELEMENT';
export const CLEAR_STORE = 'CLEAR_STORE';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SESSION_REGISTER_REQUEST = 'SESSION_REGISTER_REQUEST';
export const SESSION_REGISTER_SUCCESS = 'SESSION_REGISTER_SUCCESS';
export const SESSION_REGISTER_FAIL = 'SESSION_REGISTER_FAIL';

// student
export const STUDENT_UPDATE_REQUEST = 'STUDENT_UPDATE_REQUEST';
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS';
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL';
export const SPONSOR_UPDATE_REQUEST = 'SPONSOR_UPDATE_REQUEST';
export const SPONSOR_UPDATE_SUCCESS = 'SPONSOR_UPDATE_SUCCESS';
export const SPONSOR_UPDATE_FAIL = 'SPONSOR_UPDATE_FAIL';

// event
export const RESET_EVENT = 'RESET_EVENT';
export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const EVENT_CREATE_FAIL = 'EVENT_CREATE_FAIL';
export const EVENT_UPDATE_REQUEST = 'EVENT_UPDATE_REQUEST';
export const EVENT_UPDATE_SUCCESS = 'EVENT_UPDATE_SUCCESS';
export const EVENT_UPDATE_FAIL = 'EVENT_UPDATE_FAIL';
export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST';
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS';
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL';
export const EVENT_REGISTER_REQUEST = 'EVENT_REGISTER_REQUEST';
export const EVENT_REGISTER_SUCCESS = 'EVENT_REGISTER_SUCCESS';
export const EVENT_REGISTER_FAIL = 'EVENT_REGISTER_FAIL';
export const GET_USER_EVENT_REQUEST = 'GET_USER_EVENT_REQUEST';
export const GET_USER_EVENT_SUCCESS = 'GET_USER_EVENT_SUCCESS';
export const GET_USER_EVENT_FAIL = 'GET_USER_EVENT_FAIL';
export const GET_STUDENT_EVENT_REQUEST = 'GET_STUDENT_EVENT_REQUEST';
export const GET_STUDENT_EVENT_SUCCESS = 'GET_STUDENT_EVENT_SUCCESS';
export const GET_STUDENT_EVENT_FAIL = 'GET_STUDENT_EVENT_FAIL';
export const GET_RECOMENT_EVENT_REQUEST = 'GET_RECOMENT_EVENT_REQUEST';
export const GET_RECOMENT_EVENT_SUCCESS = 'GET_RECOMENT_EVENT_SUCCESS';
export const GET_RECOMENT_EVENT_FAIL = 'GET_RECOMENT_EVENT_FAIL';
export const SET_LIKE_REQUEST = 'SET_LIKE_REQUEST';
export const SET_LIKE_SUCCESS = 'SET_LIKE_SUCCESS';
export const SET_LIKE_FAIL = 'SET_LIKE_FAIL';
export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAIL = 'GET_EVENT_FAIL';
export const GET_CHECK_REQUEST = 'GET_CHECK_REQUEST';
export const GET_CHECK_SUCCESS = 'GET_CHECK_SUCCESS';
export const GET_CHECK_FAIL = 'GET_CHECK_FAIL';
export const SET_CHECK_REQUEST = 'SET_CHECK_REQUEST';
export const SET_CHECK_SUCCESS = 'SET_CHECK_SUCCESS';
export const SET_CHECK_FAIL = 'SET_CHECK_FAIL';
export const GET_EVENT_ALL_REQUEST = 'GET_EVENT_ALL_REQUEST';
export const GET_EVENT_ALL_SUCCESS = 'GET_EVENT_ALL_SUCCESS';
export const GET_EVENT_ALL_FAIL = 'GET_EVENT_ALL_FAIL';
export const GET_EVENT_MEMBERSHIP_REQUEST = 'GET_EVENT_MEMBERSHIP_REQUEST';
export const GET_EVENT_MEMBERSHIP_SUCCESS = 'GET_EVENT_MEMBERSHIP_SUCCESS';
export const GET_EVENT_MEMBERSHIP_FAIL = 'GET_EVENT_MEMBERSHIP_FAIL';
